### PR TITLE
Add GNOME icons

### PR DESCRIPTION
**Pull request by vanillajonathan**
I replaced the colors in the PRQL logo with Yellow 3, Red 3 and Blue 3 from the [GNOME color palette](https://developer.gnome.org/hig/reference/palette.html).

I am not sure if I should have used Orange 3 `#ff7800` instead of Yellow 3 `#f6d32d`.
I don't know if the color palette applies to brand logos too or if they're exempt.

I set the height to 112 px because that was the height of the Nautilus icon, so it is the same height on a 128 x 128 pixel grid. I am not good with graphics, but hopefully I didn't position it all too wrong on the template.

### CODE REVIEW

**Comment by max-sixty** [comment]
Thanks for the effort — but unless a) we actually need a logo like this and b) the color scheme is very strict — I think the upsides of having a logo that fits with their color scheme are outweighed by the downsides of having multiple logos out there.

Are you OK with us closing?

**Comment by vanillajonathan** [comment]
Yeah, I am okay with us closing, I just thought it would be nice if there were application icons available for different platforms such as GNOME, KDE, macOS/iOS, Android and Windows as a resource for app developers who might want to make a PRQL application or integrate PRQL into their application.

**Comment by max-sixty** [comment]
Yes. My understand is that the color schemes are suggested, rather that strict, and so folks could still use the logos. 

(but if anyone reads this and needs a logo that we don't have, please open an issue and we'll see what we can do)

**Comment by vanillajonathan** [comment]
I've previously filed issue #3 that suggests that icons should be available for different platforms.

**Pull request closed without merging**
